plugin: aws_ec2
regions:
  - eu-north-1
filters:
  tag:Project: CloudNotes
hostnames:
  - public-ip-address
compose:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ../terraform/keys/cloudnotes-key.pem
  ansible_python_interpreter: /usr/bin/python3
keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Project
    prefix: project
