plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: CloudNotes
  instance-state-name: running
keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Project
    prefix: project
compose:
  ansible_host: public_ip_address